version: '3.3'
services:
  trello-helper:
    build:
      context: trello-helper
    container_name: trello-helper
    ports:
      - "50031:22"
    volumes:
      - ./trello-helper/config.json:/home/ubuntu/trello-helper/trello_helper/config.json
    environment:
      - TZ=Asiz/Tokyo
